# Generated by Django 5.0.6 on 2024-07-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.TextField(default=None),
        ),
    ]
