# Generated by Django 5.0.6 on 2024-07-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_post_id_notification_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
