# Generated by Django 5.0.6 on 2024-07-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='Social_media\\image\\images\\default dp.jpg', upload_to='images/'),
        ),
    ]
