# Generated by Django 5.0.6 on 2024-08-23 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_post_created_at_alter_post_updated_at_ping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ping',
            new_name='Pings',
        ),
        migrations.CreateModel(
            name='PingReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyping', to='user.pings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
